### PR TITLE
Add SPICE from coco-caption

### PR DESCRIPTION
**Pull request by tgisaturday**
I've added SPICE metric from coco-caption and also updated setup. SPICE is working in python3. Needs double check.

### CODE REVIEW

**Comment by msftgits** [comment]
[CLA assistant check](https://cla.opensource.microsoft.com/Maluuba/nlg-eval?pullRequest=126) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Maluuba/nlg-eval?pullRequest=126) before we can accept your contribution.<br/><br/>:x: tgisaturday [sign now](https://cla.opensource.microsoft.com/Maluuba/nlg-eval?pullRequest=126)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Maluuba/nlg-eval?pullRequest=126) it.</sub>

**Comment by temporaer** [comment]
@tgisaturday , apologies for the looong delay in response. I see you added quite a few of jar files, do they come with some sort of license that you should also include?

**Comment by tgisaturday** [comment]
I have to go back to myself 2 years ago :) Based on my memory, what I've done is adding 

https://github.com/peteanderson80/SPICE 

to the evaluation. 

SPICE is under GNU Affero General Public License v3.0.

**Comment by temporaer** [comment]
In that case, would you be open to add the information to the 3rd party section in https://github.com/Maluuba/nlg-eval/blob/master/LICENSE.md?

**Comment by tgisaturday** [comment]
Yes I agree.

**Comment by tgisaturday** [comment]
@temporaer I included License information for SPICE in LICENSE.md. Please double check if there's anything I've missed.

**Comment by temporaer** [comment]
Thank you @tgisaturday!

**Comment by tgisaturday** [comment]
@temporaer I forgot to update README.md. Please add SPICE to Metrics section

**Comment by temporaer** [comment]
Can you please create a new PR for this? Thank you.

**Pull request merged**
